//////////////////// VEHICULE ////////////////////

###
GET http://localhost:3000/vehicules

###
GET http://localhost:3000/vehicules?marque=peugeot&model[]=307&model[]=3008

###
GET http://localhost:3000/vehicules/7

###
DELETE http://localhost:3000/vehicules/2

###
POST http://localhost:3000/vehicules
Content-Type: application/json

{
    "marque": "Renault",
    "model" : "Twingo",
    "dateFabrication" : "2005-06-10"
}

###
PUT http://localhost:3000/vehicules/1
Content-Type: application/json

{
    "marque": "Toyota"
}

//////////////////// OWNER ////////////////////

###
GET http://localhost:3000/owner

###
GET http://localhost:3000/owner/2

###
DELETE http://localhost:3000/owner/2

###
POST http://localhost:3000/owner
Content-Type: application/json

{
    "firstname" : "Laurynn",
    "lastname" : "Hildebert"
}

###
PUT http://localhost:3000/owner/2
Content-Type: application/json

{
    "lastname" : ""
}

//////////////////// CONCESSIONAIRE ////////////////////

###
GET http://localhost:3000/concessionaire

###
GET http://localhost:3000/concessionaire/2

###
DELETE http://localhost:3000/concessionaire/2

###
POST http://localhost:3000/concessionaire
Content-Type: application/json

{
    "address" : "rue de Paris",
    "proprietaire" : "Jade",
    "open" : "5bis"
}

###
PUT http://localhost:3000/concessionaire/2
Content-Type: application/json

{
    "proprietaire" : ""
}